jobs:
- substitutions:
  - type: regex
    find: "(SUMMARY:)([^:]+): (.*)."
    replace: "$1$3"
  - type: string
    find: Business-hours-jsp_schedule
    replace: In Hours
  - type: string
    find: On-call secondary
    replace: Secondary
  - type: string
    find: On-call primary
    replace: Primary
  mappings:
  - source:
      type: http
      url: https://jetstack.app.eu.opsgenie.com/webapi/webcal/getRecentSchedule?webcalToken=97201e6c52f9a4dd99e9deb42d072680b1dcbe34282d18f8cba75c28f233f747
    destination:
      type: BucketObject
      path: gs://charlieegan3-static/subpub/opsgenie

- substitutions:
  - type: string
    find: "Charlie Egan - "
    replace: ""
  mappings:
  - source:
      type: http
      url: https://app.timetastic.co.uk/Feeds/MyCalendar/68fa5be2-26f7-4199-8a30-8d50bf8f5995
    destination:
      type: BucketObject
      path: gs://charlieegan3-static/subpub/timetastic
